package com.github.manevolent.ts3j.client;

import com.github.manevolent.ts3j.api.Channel;
import com.github.manevolent.ts3j.api.Client;
import com.github.manevolent.ts3j.api.Codec;
import com.github.manevolent.ts3j.event.ChannelCreateEvent;
import com.github.manevolent.ts3j.event.ChannelDeletedEvent;
import com.github.manevolent.ts3j.event.ChannelEditedEvent;
import com.github.manevolent.ts3j.event.ChannelListEvent;
import com.github.manevolent.ts3j.event.ClientJoinEvent;
import com.github.manevolent.ts3j.event.ClientLeaveEvent;
import com.github.manevolent.ts3j.event.ClientMovedEvent;
import com.github.manevolent.ts3j.event.ClientPokeEvent;
import com.github.manevolent.ts3j.event.ClientUpdatedEvent;
import com.github.manevolent.ts3j.event.ConnectedEvent;
import com.github.manevolent.ts3j.event.DisconnectedEvent;
import com.github.manevolent.ts3j.event.TS3Listener;
import com.github.manevolent.ts3j.event.TextMessageEvent;
import com.github.manevolent.ts3j.api.TextMessageTargetMode;
import com.github.manevolent.ts3j.identity.LocalIdentity;
import com.github.manevolent.ts3j.enums.CodecType;
import com.github.manevolent.ts3j.protocol.socket.client.LocalTeamspeakClientSocket;

import java.io.File;
import java.io.IOException;
import java.net.InetSocketAddress;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.security.GeneralSecurityException;
import java.time.Clock;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Base64;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.TreeMap;
import java.util.UUID;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;
import java.util.function.Consumer;

/**
 * Adapter around the real ts3j client socket. No TeamSpeak object escapes this
 * boundary; the JavaFX layer only consumes immutable snapshots.
 */
public final class TeamSpeakGateway implements TS3Listener, AutoCloseable {
    private static final int MAX_CHAT_MESSAGES = 100;
    /** Internal TeamSpeak metadata used to discover other app instances. */
    private static final String CLIENT_SESSION_METADATA = "ts3j-client-session-v1";
    private static final String SESSION_MARKER_PREFIX = "ts3j-session-v1|";
    /** Marker emitted by the authoritative server-side timer service. */
    private static final String SERVER_SESSION_MARKER_PREFIX = "ts3j-server-session-v1|";
    private static final String SESSION_MARKER_REQUEST_PREFIX = "ts3j-session-request-v1|";
    /** Broadcast request used when a restricted identity cannot resolve peer ids. */
    private static final String SESSION_CHANNEL_REQUEST_PREFIX =
            "ts3j-session-channel-request-v1|";
    private static final long PENDING_MARKER_MAX_AGE_SECONDS = 30L;
    /**
     * Some TeamSpeak servers reject the low-security identity generated by the
     * original client defaults. Keep the identity stable, but provision it at a
     * security level accepted by the normal TeamSpeak client handshake.
     */
    static final int MINIMUM_IDENTITY_SECURITY = 8;

    private final VoiceSessionCoordinator sessions;
    private final Clock clock;
    private final ChannelChatRepository chatRepository;
    private final String eventSource = UUID.randomUUID().toString();
    private final ExecutorService ioExecutor = Executors.newSingleThreadExecutor(r -> {
        Thread thread = new Thread(r, "ts3j-client-io");
        thread.setDaemon(true);
        return thread;
    });
    private final ScheduledExecutorService sessionMarkerRetryExecutor =
            Executors.newSingleThreadScheduledExecutor(r -> {
                Thread thread = new Thread(r, "ts3j-client-session-marker-retry");
                thread.setDaemon(true);
                return thread;
            });
    private final List<Consumer<GatewaySnapshot>> listeners = new CopyOnWriteArrayList<>();
    private final List<Consumer<TeamSpeakActivity>> activityListeners = new CopyOnWriteArrayList<>();
    private final Map<Integer, ChannelView> channels = new HashMap<>();
    private final Map<Integer, ClientView> clients = new HashMap<>();
    /** Client ids reserved for ServerQuery helpers; never render or count them. */
    private final Set<Integer> nonUserClientIds = new HashSet<>();
    private final Map<Integer, List<ChannelTextMessage>> channelMessages = new HashMap<>();
    private final Map<Integer, Integer> channelHistoryBoundaries = new HashMap<>();
    private final Map<String, Instant> recentEventSignatures = new HashMap<>();
    private final Map<String, Instant> recentActivitySignatures = new HashMap<>();
    private final Map<SessionKey, PendingSessionMarker> pendingSessionMarkers = new HashMap<>();
    private final Map<SessionKey, PendingServerSessionMarker> pendingServerSessionMarkers = new HashMap<>();
    private final Map<SessionKey, Instant> latestServerSessionStarts = new HashMap<>();
    private final Map<SessionKey, Set<Integer>> pendingSessionMarkerRequests = new HashMap<>();
    private final Set<SessionKey> pendingSessionChannelRequests = new HashSet<>();
    private final Map<String, Instant> recentSessionMarkerSends = new HashMap<>();
    private final Map<String, Instant> recentSessionMarkerPeerRequests = new HashMap<>();

    private volatile LocalTeamspeakClientSocket socket;
    private volatile AudioDeviceService audioDeviceService;
    private volatile TeamSpeakAudioBridge audioBridge;
    private volatile ClientVolumeStore clientVolumeStore;
    private volatile ConnectionConfig config;
    private volatile ConnectionStatus status = ConnectionStatus.DISCONNECTED;
    private volatile String errorMessage = "";
    private volatile String chatHistoryWarning = "";
    private volatile int currentChannelId = -1;
    private volatile long eventSequence;
    private volatile boolean initialSync;
    private volatile boolean sessionStateReady = true;
    /** True when the server accepted the connection but hid one or more listings. */
    private volatile boolean permissionsLimited;
    private volatile boolean closed;

    public TeamSpeakGateway(VoiceSessionCoordinator sessions) {
        this(sessions, Clock.systemUTC(), new FileChannelChatRepository(defaultChatHistoryDirectory()));
    }

    public TeamSpeakGateway(VoiceSessionCoordinator sessions, Clock clock) {
        this(sessions, clock, new FileChannelChatRepository(defaultChatHistoryDirectory()));
    }

    TeamSpeakGateway(VoiceSessionCoordinator sessions, Clock clock,
                     ChannelChatRepository chatRepository) {
        if (sessions == null || clock == null) throw new IllegalArgumentException("sessions/clock");
        if (chatRepository == null) throw new IllegalArgumentException("chatRepository");
        this.sessions = sessions;
        this.clock = clock;
        this.chatRepository = chatRepository;
    }

    public void addListener(Consumer<GatewaySnapshot> listener) {
        if (listener != null) listeners.add(listener);
    }

    public void removeListener(Consumer<GatewaySnapshot> listener) {
        listeners.remove(listener);
    }

    public void addActivityListener(Consumer<TeamSpeakActivity> listener) {
        if (listener != null) activityListeners.add(listener);
    }

    public void removeActivityListener(Consumer<TeamSpeakActivity> listener) {
        activityListeners.remove(listener);
    }

    /**
     * Attaches the selected Java Sound devices to ts3j's real UDP voice
     * transport. The setter is intentionally package-private: the desktop
     * shell owns hardware lifetime while this gateway owns TeamSpeak state.
     */
    synchronized void setAudioDeviceService(AudioDeviceService service) {
        if (audioBridge != null) audioBridge.close();
        audioDeviceService = service;
        audioBridge = null;
    }

    synchronized void setClientVolumeStore(ClientVolumeStore store) {
        clientVolumeStore = store;
    }

    public synchronized GatewaySnapshot snapshot() {
        return createSnapshot();
    }

    public synchronized void connect(final ConnectionConfig connectionConfig) {
        if (closed) throw new IllegalStateException("gateway is closed");
        if (status == ConnectionStatus.CONNECTING
                || status == ConnectionStatus.CONNECTED_NO_CHANNEL
                || status == ConnectionStatus.CONNECTED_IN_CHANNEL) {
            return;
        }
        if (connectionConfig == null) throw new IllegalArgumentException("connectionConfig");
        config = connectionConfig;
        // Session starts are no longer persisted by each desktop instance.
        // The server-side ts3j-session-timer is authoritative; this in-memory
        // repository only carries the occupied-channel view used by JavaFX.
        sessions.useRepository(new InMemoryVoiceSessionRepository());
        // A persisted record cannot prove that the server stayed occupied
        // while this client was disconnected. Start this connection from the
        // server's next authoritative snapshot; a peer marker can restore a
        // known start when another client is already present.
        sessions.reconcile(connectionConfig.serverId(),
                Collections.<Integer, java.util.Collection<Integer>>emptyMap(), clock.instant(),
                gatewayEventId("connection-reset", Collections.<String, String>emptyMap()), 0L);
        status = ConnectionStatus.CONNECTING;
        errorMessage = "";
        chatHistoryWarning = "";
        permissionsLimited = false;
        nonUserClientIds.clear();
        pendingSessionMarkers.clear();
        pendingServerSessionMarkers.clear();
        latestServerSessionStarts.clear();
        pendingSessionMarkerRequests.clear();
        pendingSessionChannelRequests.clear();
        recentSessionMarkerSends.clear();
        recentSessionMarkerPeerRequests.clear();
        initialSync = true;
        sessionStateReady = false;
        channelMessages.clear();
        channelHistoryBoundaries.clear();
        loadChatHistory(connectionConfig.serverId());
        publish();

        final LocalTeamspeakClientSocket nextSocket = new LocalTeamspeakClientSocket();
        nextSocket.addListener(this);
        nextSocket.setNickname(connectionConfig.getNickname());
        nextSocket.setOption("client.meta_data", CLIENT_SESSION_METADATA);
        final TeamSpeakAudioBridge nextAudioBridge = audioDeviceService == null ? null
                : new TeamSpeakAudioBridge(audioDeviceService, this::currentVoiceCodec,
                        this::currentVoiceVolumeDb);
        if (nextAudioBridge != null) {
            nextAudioBridge.setMuted(false);
            audioDeviceService.clearCaptureFrames();
            nextSocket.setMicrophone(nextAudioBridge);
            nextSocket.setVoiceHandler(packet -> {
                TeamSpeakAudioBridge active = audioBridge;
                if (active == nextAudioBridge) active.handleVoicePacket(packet);
            });
        }
        audioBridge = nextAudioBridge;
        socket = nextSocket;

        ioExecutor.submit(new Runnable() {
            @Override
            public void run() {
                try {
                    nextSocket.setIdentity(loadIdentity());
                    nextSocket.connect(new InetSocketAddress(connectionConfig.getHost(),
                            connectionConfig.getPort()), connectionConfig.getPassword(), 15000L);
                    // onConnected schedules subscription/refresh on this same single
                    // executor after connect() returns, avoiding listener deadlock.
                } catch (Throwable error) {
                    synchronized (TeamSpeakGateway.this) {
                        status = ConnectionStatus.ERROR;
                        errorMessage = friendlyMessage(error);
                        sessionStateReady = false;
                        if (audioBridge == nextAudioBridge) {
                            if (audioBridge != null) audioBridge.close();
                            audioBridge = null;
                        }
                    }
                    publish();
                    closeSocket(nextSocket);
                }
            }
        });
    }

    public synchronized void disconnect() {
        final LocalTeamspeakClientSocket current = socket;
        if (current == null || status == ConnectionStatus.DISCONNECTED) return;
        ioExecutor.submit(new Runnable() {
            @Override
            public void run() {
                try {
                    current.disconnect();
                } catch (Throwable error) {
                    synchronized (TeamSpeakGateway.this) {
                        errorMessage = friendlyMessage(error);
                    }
                } finally {
                    closeSocket(current);
                    synchronized (TeamSpeakGateway.this) {
                        if (socket == current) {
                            socket = null;
                            status = ConnectionStatus.DISCONNECTED;
                            currentChannelId = -1;
                            clients.clear();
                            channels.clear();
                            channelMessages.clear();
                            channelHistoryBoundaries.clear();
                            chatHistoryWarning = "";
                            permissionsLimited = false;
                            pendingSessionMarkers.clear();
                            pendingServerSessionMarkers.clear();
                            latestServerSessionStarts.clear();
                            pendingSessionMarkerRequests.clear();
                            pendingSessionChannelRequests.clear();
                            recentSessionMarkerSends.clear();
                            recentSessionMarkerPeerRequests.clear();
                            if (audioBridge != null) audioBridge.close();
                            audioBridge = null;
                            initialSync = false;
                            sessionStateReady = true;
                        }
                    }
                    publish();
                }
            }
        });
    }

    /** The full-client protocol exposes the away flag through clientupdate. */
    public boolean supportsAwayStatus() { return true; }

    /** Manual microphone mute is represented by client_input_muted. */
    public boolean supportsMicrophoneMute() { return true; }

    /** Speakers/headphones mute is represented by client_output_muted. */
    public boolean supportsAudioMute() { return true; }

    /**
     * Toggles the away flag of the local TeamSpeak client. The server echoes
     * the accepted value through notifyclientupdated, while the gateway also
     * updates its local immutable snapshot after the command acknowledgement.
     */
    public synchronized void toggleAwayStatus() {
        ClientView local = requireLocalClient();
        queueClientFlagUpdate("client_away", !local.isAway());
    }

    public synchronized void setAwayStatus(boolean away) {
        requireLocalClient();
        queueClientFlagUpdate("client_away", away);
    }

    public synchronized void toggleMicrophoneMute() {
        ClientView local = requireLocalClient();
        queueClientFlagUpdate("client_input_muted", !local.isInputMuted());
    }

    public synchronized void setMicrophoneMuted(boolean muted) {
        requireLocalClient();
        if (audioBridge != null) audioBridge.setMuted(muted);
        queueClientFlagUpdate("client_input_muted", muted);
    }

    public synchronized void toggleAudioMute() {
        ClientView local = requireLocalClient();
        queueClientFlagUpdate("client_output_muted", !local.isOutputMuted());
    }

    public synchronized void setAudioMuted(boolean muted) {
        requireLocalClient();
        if (audioBridge != null) audioBridge.setOutputMuted(muted);
        queueClientFlagUpdate("client_output_muted", muted);
    }

    private ClientView requireLocalClient() {
        LocalTeamspeakClientSocket current = socket;
        if (current == null || (status != ConnectionStatus.CONNECTED_IN_CHANNEL
                && status != ConnectionStatus.CONNECTED_NO_CHANNEL)) {
            throw new IllegalStateException("No hay una conexión activa a TeamSpeak.");
        }
        ClientView local = clients.get(current.getClientId());
        if (local == null) {
            throw new IllegalStateException("El estado de tu cliente todavía no está disponible.");
        }
        return local;
    }

    private void queueClientFlagUpdate(final String property, final boolean value) {
        final LocalTeamspeakClientSocket expectedSocket = socket;
        ioExecutor.submit(() -> {
            try {
                if ("client_away".equals(property)) {
                    expectedSocket.setAway(value);
                } else if ("client_input_muted".equals(property)) {
                    expectedSocket.setInputMuted(value);
                } else if ("client_output_muted".equals(property)) {
                    expectedSocket.setOutputMuted(value);
                } else {
                    throw new IllegalArgumentException("Propiedad de cliente no soportada: " + property);
                }
                synchronized (TeamSpeakGateway.this) {
                    if (socket == expectedSocket) {
                        ClientView before = clients.get(expectedSocket.getClientId());
                        applyLocalClientFlag(property, value);
                        if (before != null && flagChanged(before, property, value)) {
                            emitActivity(activityForClientFlag(property, value));
                        }
                    }
                }
                publish();
            } catch (Throwable error) {
                synchronized (TeamSpeakGateway.this) {
                    errorMessage = friendlyMessage(error);
                }
                publish();
            }
        });
    }

    private void applyLocalClientFlag(String property, boolean value) {
        LocalTeamspeakClientSocket current = socket;
        if (current == null) return;
        int clientId = current.getClientId();
        ClientView local = clients.get(clientId);
        if (local == null) return;
        if ("client_away".equals(property)) {
            clients.put(clientId, local.withAway(value));
        } else if ("client_input_muted".equals(property)) {
            clients.put(clientId, local.withInputMuted(value));
            if (audioBridge != null) audioBridge.setMuted(value);
        } else if ("client_output_muted".equals(property)) {
            clients.put(clientId, local.withOutputMuted(value));
            if (audioBridge != null) audioBridge.setOutputMuted(value);
        }
    }

    private static boolean flagChanged(ClientView before, String property, boolean value) {
        if ("client_away".equals(property)) return before.isAway() != value;
        if ("client_input_muted".equals(property)) return before.isInputMuted() != value;
        if ("client_output_muted".equals(property)) return before.isOutputMuted() != value;
        return false;
    }

    private TeamSpeakActivity activityForClientFlag(String property, boolean value) {
        TeamSpeakActivity.Type type;
        if ("client_away".equals(property)) {
            type = value ? TeamSpeakActivity.Type.AWAY_ENABLED : TeamSpeakActivity.Type.AWAY_DISABLED;
        } else if ("client_input_muted".equals(property)) {
            type = value ? TeamSpeakActivity.Type.MICROPHONE_MUTED : TeamSpeakActivity.Type.MICROPHONE_UNMUTED;
        } else {
            type = value ? TeamSpeakActivity.Type.AUDIO_MUTED : TeamSpeakActivity.Type.AUDIO_UNMUTED;
        }
        return activity(type, "", "", "");
    }

    /**
     * Queues a channel-chat message through ts3j. TeamSpeak validates whether
     * this identity may write to the channel; a voice codec does not disable
     * channel chat.
     */
    public synchronized void sendChannelMessage(final int channelId, final String message) {
        if (message == null || message.trim().isEmpty()) return;
        final LocalTeamspeakClientSocket current = socket;
        if (current == null || (status != ConnectionStatus.CONNECTED_IN_CHANNEL
                && status != ConnectionStatus.CONNECTED_NO_CHANNEL)) {
            throw new IllegalStateException("No hay una conexión activa a TeamSpeak.");
        }
        final String sender = config == null ? "Tú" : config.getNickname();
        final String serverId = config == null ? "" : config.serverId();
        // This cue is feedback for the local send action. Emit it when the
        // command is accepted into our I/O queue instead of waiting for the
        // network round-trip or a possible server echo.
        emitActivity(new TeamSpeakActivity(TeamSpeakActivity.Type.CHAT_SENT,
                sender, "", channelName(channelId), serverName()));
        ioExecutor.submit(() -> {
            try {
                current.sendChannelMessage(channelId, message);
                // The full-client protocol does not echo a channel message to
                // its sender on every server version.  Only commit the local
                // copy after TeamSpeak accepted the command, then let a later
                // notifytextmessage event deduplicate it if the server echoes.
                ChannelTextMessage localMessage = new ChannelTextMessage(
                        channelId, sender, message, clock.instant());
                boolean appended;
                synchronized (TeamSpeakGateway.this) {
                    appended = appendChannelMessageIfNew(localMessage);
                }
                if (appended) persistChannelMessage(serverId, localMessage);
                publish();
            } catch (Throwable error) {
                synchronized (TeamSpeakGateway.this) {
                    errorMessage = friendlyMessage(error);
                }
                publish();
            }
        });
    }

    @Override
    public void onConnected(ConnectedEvent event) {
        synchronized (this) {
            status = ConnectionStatus.CONNECTED_NO_CHANNEL;
            errorMessage = "";
        }
        emitActivity(activity(TeamSpeakActivity.Type.CONNECTED, "", "", ""));
        publish();
        ioExecutor.submit(new Runnable() {
            @Override
            public void run() {
                LocalTeamspeakClientSocket current = socket;
                if (current == null) return;
                try {
                    try {
                        current.subscribeAll();
                    } catch (Throwable error) {
                        if (!isInsufficientClientPermissions(error)) throw error;
                        // Some restricted server groups can subscribe to the
                        // visible channel but cannot list every channel. The
                        // notify events and the current-client fallback below
                        // still provide a useful connected view.
                        permissionsLimited = true;
                    }
                    refreshFromServer(current);
                } catch (Throwable error) {
                    synchronized (TeamSpeakGateway.this) {
                        status = ConnectionStatus.ERROR;
                        errorMessage = friendlyMessage(error);
                    }
                    publish();
                }
            }
        });
    }

    @Override
    public void onTextMessage(TextMessageEvent event) {
        if (event == null) return;
        if (event.getTargetMode() == TextMessageTargetMode.CLIENT
                || event.getTargetMode() == TextMessageTargetMode.CHANNEL) {
            if (consumeServerSessionMarker(event)) return;
            if (consumeSessionMarker(event)) return;
            if (consumeSessionMarkerRequest(event)) return;
        }
        if (event.getTargetMode() != TextMessageTargetMode.CHANNEL) return;
        int channelId = event.getTargetChannelId();
        if (channelId < 0) channelId = resolveChannelFromTextEvent(event);
        String message = event.getMessage();
        if (channelId < 0 || message == null || message.isEmpty()) return;
        String sender = event.getInvokerName();
        if (sender == null || sender.isEmpty()) {
            int invokerId = event.getInvokerId();
            sender = invokerId < 0 ? "Usuario" : "Usuario " + invokerId;
        }
        ChannelTextMessage received = new ChannelTextMessage(channelId, sender, message, clock.instant());
        boolean appended = false;
        synchronized (this) {
            boolean localSender = event.getInvokerId() >= 0 && event.getInvokerId() == localClientId();
            if (!localSender || !hasRecentMessage(channelId, message)) {
                appendChannelMessage(received);
                appended = true;
            }
        }
        if (appended) persistChannelMessage(configuredServerId(), received);
        if (appended && event.getInvokerId() != localClientId()) {
            emitActivity(new TeamSpeakActivity(TeamSpeakActivity.Type.CHAT_RECEIVED,
                    sender, "", channelName(channelId), serverName()));
        }
        publish();
    }

    /**
     * Consumes the marker sent by the server-side authority. It deliberately
     * does not add the ServerQuery bot as a visible channel user and it can
     * replace a locally inferred start, because the server owns the 0-to-1
     * transition.
     */
    private boolean consumeServerSessionMarker(TextMessageEvent event) {
        String message = event.getMessage();
        if (message == null || !message.startsWith(SERVER_SESSION_MARKER_PREFIX)) return false;
        ServerSessionMarker marker = parseServerSessionMarker(message);
        if (marker == null) return true;
        String serverId = configuredServerId();
        if (!serverId.equals(marker.serverId)) return true;
        Instant now = clock.instant();
        if (marker.serverNow != null && marker.start.isAfter(marker.serverNow.plusSeconds(5L))) return true;
        Instant effectiveStart = marker.start;
        if (marker.serverNow != null) {
            // TeamSpeak and the timer service use UTC. Compensate for a small
            // workstation clock skew so every client displays the same age.
            java.time.Duration offset = java.time.Duration.between(now, marker.serverNow);
            effectiveStart = marker.start.minus(offset);
        }
        SessionKey key = new SessionKey(marker.serverId, marker.channelId);
        synchronized (this) {
            Instant previous = latestServerSessionStarts.get(key);
            if (previous != null && marker.start.isBefore(previous)) return true;
            latestServerSessionStarts.put(key, marker.start);
        }
        String eventId = "server-session-marker:" + marker.sessionId + ":"
                + marker.serverId + ":" + marker.channelId;
        adoptOrQueueServerSessionStart(key, effectiveStart, eventId);
        publish();
        return true;
    }

    private static ServerSessionMarker parseServerSessionMarker(String message) {
        String[] fields = message.split("\\|", -1);
        if (fields.length != 6 || !SERVER_SESSION_MARKER_PREFIX.substring(0,
                SERVER_SESSION_MARKER_PREFIX.length() - 1).equals(fields[0])) return null;
        try {
            String serverId = new String(Base64.getUrlDecoder().decode(fields[1]),
                    java.nio.charset.StandardCharsets.UTF_8);
            int channelId = Integer.parseInt(fields[2]);
            String sessionId = fields[3].trim();
            Instant start = Instant.parse(fields[4]);
            Instant serverNow = Instant.parse(fields[5]);
            if (serverId.trim().isEmpty() || channelId < 0 || sessionId.isEmpty()) return null;
            return new ServerSessionMarker(serverId, channelId, sessionId, start, serverNow);
        } catch (RuntimeException error) {
            return null;
        }
    }

    private void adoptOrQueueServerSessionStart(SessionKey key, Instant start, String eventId) {
        if (key == null || start == null) return;
        if (initialSync || !sessionStateReady) {
            synchronized (this) {
                pendingServerSessionMarkers.put(key,
                        new PendingServerSessionMarker(start, clock.instant(), eventId));
            }
            return;
        }
        VoiceRoomSession current = sessions.snapshot().get(key);
        if (current != null && current.isOccupied()) {
            sessions.adoptServerSessionStart(key.getServerId(), key.getChannelId(), start, eventId);
            return;
        }
        synchronized (this) {
            pendingServerSessionMarkers.put(key,
                    new PendingServerSessionMarker(start, clock.instant(), eventId));
        }
    }

    private void applyPendingServerSessionMarkers() {
        Instant now = clock.instant();
        Map<SessionKey, PendingServerSessionMarker> pending;
        synchronized (this) {
            pending = new HashMap<>(pendingServerSessionMarkers);
        }
        for (Map.Entry<SessionKey, PendingServerSessionMarker> entry : pending.entrySet()) {
            PendingServerSessionMarker marker = entry.getValue();
            if (marker == null || now.minusSeconds(PENDING_MARKER_MAX_AGE_SECONDS)
                    .isAfter(marker.receivedAt)) {
                synchronized (this) { pendingServerSessionMarkers.remove(entry.getKey()); }
                continue;
            }
            VoiceRoomSession current = sessions.snapshot().get(entry.getKey());
            if (current == null || !current.isOccupied()) continue;
            sessions.adoptServerSessionStart(entry.getKey().getServerId(),
                    entry.getKey().getChannelId(), marker.start, marker.eventId);
            synchronized (this) { pendingServerSessionMarkers.remove(entry.getKey()); }
        }
    }

    /**
     * Consumes the private, app-to-app session marker without exposing it in
     * the normal chat UI. A marker is trusted only while the channel remains
     * occupied; the reducer itself also refuses to create a session from an
     * empty channel.
     */
    private boolean consumeSessionMarker(TextMessageEvent event) {
        String message = event.getMessage();
        if (message == null || !message.startsWith(SESSION_MARKER_PREFIX)) return false;
        SessionMarker marker = parseSessionMarker(message);
        if (marker == null) return true;
        String serverId = configuredServerId();
        if (!serverId.equals(marker.serverId)) return true;
        if (marker.start.isAfter(clock.instant().plusSeconds(5L))) return true;

        int senderId = event.getInvokerId();
        boolean channelTarget = event.getTargetMode() == TextMessageTargetMode.CHANNEL;
        // Do not reject a marker merely because the cached client map says the
        // sender was in another channel. During a disconnect/rejoin that map
        // can be one event behind. We still distinguish whether the sender is
        // proven present so a private, delayed marker cannot resurrect a peer
        // after the channel became empty.
        if (channelTarget
                && event.getTargetChannelId() >= 0
                && event.getTargetChannelId() != marker.channelId) return true;
        VoiceRoomSession occupied = sessions.snapshot().get(
                new SessionKey(marker.serverId, marker.channelId));
        boolean peerProvenPresent = channelTarget;
        if (senderId >= 0) {
            synchronized (this) {
                ClientView sender = clients.get(senderId);
                peerProvenPresent = peerProvenPresent
                        || (sender != null && sender.getChannelId() == marker.channelId);
            }
            peerProvenPresent = peerProvenPresent
                    || (occupied != null && occupied.containsUser(senderId))
                    || hasRecentSessionMarkerPeerRequest(marker.serverId, marker.channelId, senderId);
            // Both channel broadcasts and private responses prove that an app
            // instance is present. Record that hidden peer before adopting an
            // older start; otherwise a restricted client can keep protecting
            // its fresh local bootstrap and never converge to the existing
            // session. This also covers a private marker arriving before its
            // matching request after a reconnect.
            if (peerProvenPresent && occupied != null && occupied.isOccupied()) {
                rememberSessionMarkerPeer(marker.serverId, marker.channelId, senderId);
            }
        }
        if (senderId >= 0 && peerProvenPresent) {
            forgetRecentSessionMarkerPeerRequest(marker.serverId, marker.channelId, senderId);
        }
        String eventId = "session-marker:" + senderId + ":" + marker.channelId
                + ":" + marker.start;
        adoptOrQueueSessionStart(marker.serverId, marker.channelId, marker.start, eventId,
                peerProvenPresent ? senderId : -1);
        publish();
        return true;
    }

    /**
     * Handles the explicit request sent by a newly connected app instance.
     * This path does not require clientinfo/client metadata permissions: the
     * private message itself identifies the peer that needs the marker.
     */
    private boolean consumeSessionMarkerRequest(TextMessageEvent event) {
        String message = event.getMessage();
        if (message == null || (!message.startsWith(SESSION_MARKER_REQUEST_PREFIX)
                && !message.startsWith(SESSION_CHANNEL_REQUEST_PREFIX))) return false;
        SessionMarkerRequest request = parseSessionMarkerRequest(message);
        SessionChannelRequest channelRequest = parseSessionChannelRequest(message);
        if (request == null && channelRequest == null) return true;
        boolean broadcast = channelRequest != null;
        int requestedChannelId = broadcast ? channelRequest.channelId : request.channelId;
        String requestedServerId = broadcast ? channelRequest.serverId : request.serverId;
        String serverId = configuredServerId();
        if (!serverId.equals(requestedServerId)) return true;
        if (broadcast && event.getTargetMode() != TextMessageTargetMode.CHANNEL) return true;
        if (broadcast && event.getTargetChannelId() >= 0
                && event.getTargetChannelId() != requestedChannelId) return true;

        int requesterId = event.getInvokerId();
        if (requesterId < 0 && !broadcast) return true;
        synchronized (this) {
            // For a channel broadcast, the server's target channel is the
            // authoritative route.  The local client cache can be one event
            // behind during a leave/rejoin, so validating the stale entry
            // would reject the request needed to recover the shared start.
            if (!broadcast) {
                ClientView requester = clients.get(requesterId);
                if (requester != null && requester.getChannelId() != requestedChannelId) return true;
            }
            if (initialSync || !sessionStateReady) {
                SessionKey key = new SessionKey(requestedServerId, requestedChannelId);
                if (broadcast) {
                    pendingSessionChannelRequests.add(key);
                } else {
                    Set<Integer> requesters = pendingSessionMarkerRequests.get(key);
                    if (requesters == null) {
                        requesters = new HashSet<>();
                        pendingSessionMarkerRequests.put(key, requesters);
                    }
                    requesters.add(requesterId);
                }
                return true;
            }
        }
        rememberSessionMarkerPeer(requestedServerId, requestedChannelId, requesterId);
        if (sessionMarker(requestedChannelId) != null) {
            if (broadcast) {
                respondToChannelSessionMarkerRequest(requestedChannelId);
            } else {
                respondToSessionMarkerRequest(requesterId, requestedChannelId);
            }
        }
        if (broadcast) return true;
        // A newly connected client may not know its own start yet. Ask the
        // requester back as well so an already occupied peer can answer;
        // request de-duplication prevents an unknown/unknown pair from
        // bouncing requests forever.
        queueSessionMarkerRequest(requesterId, requestedChannelId);
        return true;
    }

    private static SessionMarker parseSessionMarker(String message) {
        String[] fields = message.split("\\|", -1);
        if (fields.length != 4 || !SESSION_MARKER_PREFIX.substring(0,
                SESSION_MARKER_PREFIX.length() - 1).equals(fields[0])) return null;
        try {
            String serverId = new String(Base64.getUrlDecoder().decode(fields[1]),
                    java.nio.charset.StandardCharsets.UTF_8);
            int channelId = Integer.parseInt(fields[2]);
            Instant start = Instant.parse(fields[3]);
            if (serverId.trim().isEmpty() || channelId < 0) return null;
            return new SessionMarker(serverId, channelId, start);
        } catch (RuntimeException error) {
            return null;
        }
    }

    private static SessionMarkerRequest parseSessionMarkerRequest(String message) {
        String[] fields = message.split("\\|", -1);
        if (fields.length != 3 || !SESSION_MARKER_REQUEST_PREFIX.substring(0,
                SESSION_MARKER_REQUEST_PREFIX.length() - 1).equals(fields[0])) return null;
        try {
            String serverId = new String(Base64.getUrlDecoder().decode(fields[1]),
                    java.nio.charset.StandardCharsets.UTF_8);
            int channelId = Integer.parseInt(fields[2]);
            if (serverId.trim().isEmpty() || channelId < 0) return null;
            return new SessionMarkerRequest(serverId, channelId);
        } catch (RuntimeException error) {
            return null;
        }
    }

    private static SessionChannelRequest parseSessionChannelRequest(String message) {
        String[] fields = message.split("\\|", -1);
        if (fields.length != 3 || !SESSION_CHANNEL_REQUEST_PREFIX.substring(0,
                SESSION_CHANNEL_REQUEST_PREFIX.length() - 1).equals(fields[0])) return null;
        try {
            String serverId = new String(Base64.getUrlDecoder().decode(fields[1]),
                    java.nio.charset.StandardCharsets.UTF_8);
            int channelId = Integer.parseInt(fields[2]);
            if (serverId.trim().isEmpty() || channelId < 0) return null;
            return new SessionChannelRequest(serverId, channelId);
        } catch (RuntimeException error) {
            return null;
        }
    }

    private void adoptOrQueueSessionStart(String serverId, int channelId,
                                          Instant start, String eventId,
                                          int peerId) {
        SessionKey key = new SessionKey(serverId, channelId);
        // During the initial snapshot the repository can still contain a
        // persisted timer from an older occupancy. Defer peer markers until
        // that snapshot has classified the channel, otherwise a fresh marker
        // can be compared against (and rejected by) the stale timer.
        if (initialSync || !sessionStateReady) {
            synchronized (this) {
                pendingSessionMarkers.put(key, new PendingSessionMarker(start, clock.instant(),
                        peerId));
            }
            return;
        }
        VoiceRoomSession current = sessions.snapshot().get(key);
        if (current != null && current.isOccupied()) {
            sessions.adoptSessionStart(serverId, channelId, start, eventId);
            return;
        }
        synchronized (this) {
            pendingSessionMarkers.put(key, new PendingSessionMarker(start, clock.instant(),
                    peerId));
        }
    }

    private void applyPendingSessionMarkers() {
        Instant now = clock.instant();
        Map<SessionKey, PendingSessionMarker> pending;
        synchronized (this) {
            pending = new HashMap<>(pendingSessionMarkers);
        }
        for (Map.Entry<SessionKey, PendingSessionMarker> entry : pending.entrySet()) {
            PendingSessionMarker marker = entry.getValue();
            if (marker == null || now.minusSeconds(PENDING_MARKER_MAX_AGE_SECONDS)
                    .isAfter(marker.receivedAt)) {
                synchronized (this) {
                    pendingSessionMarkers.remove(entry.getKey());
                }
                continue;
            }
            VoiceRoomSession current = sessions.snapshot().get(entry.getKey());
            if (current == null || !current.isOccupied()) continue;
            if (marker.peerId >= 0) {
                // A marker can arrive before a restricted snapshot reveals
                // its sender (for either a private response or a channel
                // broadcast). Preserve that hidden presence before comparing
                // the marker with a local-only bootstrap.
                rememberSessionMarkerPeer(entry.getKey().getServerId(),
                        entry.getKey().getChannelId(), marker.peerId);
                current = sessions.snapshot().get(entry.getKey());
                if (current == null || !current.isOccupied()) continue;
            }
            sessions.adoptSessionStart(entry.getKey().getServerId(), entry.getKey().getChannelId(),
                    marker.start, "pending-session-marker:" + entry.getKey());
            synchronized (this) {
                pendingSessionMarkers.remove(entry.getKey());
            }
        }
    }

    private void respondToPendingSessionMarkerRequests() {
        if (initialSync || !sessionStateReady) return;
        Map<SessionKey, Set<Integer>> pending;
        Set<SessionKey> pendingChannels;
        synchronized (this) {
            pending = new HashMap<>();
            for (Map.Entry<SessionKey, Set<Integer>> entry : pendingSessionMarkerRequests.entrySet()) {
                pending.put(entry.getKey(), new HashSet<>(entry.getValue()));
            }
            pendingChannels = new HashSet<>(pendingSessionChannelRequests);
        }
        for (Map.Entry<SessionKey, Set<Integer>> entry : pending.entrySet()) {
            SessionKey key = entry.getKey();
            boolean markerKnown = sessionMarker(key.getChannelId()) != null;
            for (Integer requesterId : entry.getValue()) {
                if (requesterId == null) continue;
                rememberSessionMarkerPeer(key.getServerId(), key.getChannelId(), requesterId);
                if (markerKnown) {
                    respondToSessionMarkerRequest(requesterId, key.getChannelId());
                }
                queueSessionMarkerRequest(requesterId, key.getChannelId());
            }
            synchronized (this) {
                pendingSessionMarkerRequests.remove(key);
            }
        }
        for (SessionKey key : pendingChannels) {
            if (sessionMarker(key.getChannelId()) != null) {
                respondToChannelSessionMarkerRequest(key.getChannelId());
            }
            synchronized (this) {
                pendingSessionChannelRequests.remove(key);
            }
        }
    }

    private void rememberSessionMarkerPeer(String serverId, int channelId, int peerId) {
        if (serverId == null || serverId.isEmpty() || channelId < 0 || peerId < 0
                || peerId == localClientId()) return;
        sessions.join(serverId, channelId, peerId, clock.instant(), true,
                "session-marker-peer:" + peerId + ":" + channelId, 0L);
    }

    private void respondToSessionMarkerRequest(final int peerId, final int channelId) {
        if (peerId < 0 || channelId < 0) return;
        final LocalTeamspeakClientSocket expectedSocket = socket;
        if (expectedSocket == null) return;
        ioExecutor.submit(new Runnable() {
            @Override
            public void run() {
                try {
                    if (socket != expectedSocket || initialSync || !sessionStateReady) return;
                    String marker = sessionMarker(channelId);
                    if (marker == null) return;
                    if (!rememberSessionMarkerSend("response:" + peerId + ":"
                            + channelId + ":" + marker)) return;
                    expectedSocket.sendPrivateMessage(peerId, marker);
                } catch (Throwable ignored) {
                    // A marker is an optional convergence aid; a denied
                    // private message must never break protocol processing.
                }
            }
        });
    }

    /** Sends the known start to every app instance subscribed to this channel. */
    private void respondToChannelSessionMarkerRequest(final int channelId) {
        if (channelId < 0) return;
        final LocalTeamspeakClientSocket expectedSocket = socket;
        if (expectedSocket == null) return;
        ioExecutor.submit(new Runnable() {
            @Override
            public void run() {
                try {
                    if (socket != expectedSocket || initialSync || !sessionStateReady) return;
                    String marker = sessionMarker(channelId);
                    if (marker == null) return;
                    // A channel broadcast is the response to a fresh
                    // occupancy transition. Do not suppress it using the
                    // sender's old reconnect window: a client may have left
                    // immediately after the previous response and therefore
                    // needs the marker again when it re-enters.
                    expectedSocket.sendChannelMessage(channelId, marker);
                } catch (Throwable ignored) {
                    // A marker is an optional convergence aid.
                }
            }
        });
    }

    private void queueSessionMarkerRequest(final int peerId, final int channelId) {
        if (peerId < 0 || channelId < 0) return;
        final LocalTeamspeakClientSocket expectedSocket = socket;
        if (expectedSocket == null) return;
        ioExecutor.submit(new Runnable() {
            @Override
            public void run() {
                sendSessionMarkerRequest(expectedSocket, peerId, channelId);
            }
        });
    }

    private void sendSessionMarkerRequest(LocalTeamspeakClientSocket expectedSocket,
                                          int peerId, int channelId) {
        try {
            if (socket != expectedSocket || initialSync || !sessionStateReady) return;
            if (!rememberSessionMarkerSend("request:" + peerId + ":" + channelId)) return;
            rememberRecentSessionMarkerPeerRequest(configuredServerId(), channelId, peerId);
            expectedSocket.sendPrivateMessage(peerId, sessionMarkerRequest(channelId));
        } catch (Throwable ignored) {
            // The optional request is best effort and must not break event
            // processing when a server denies private messages.
        }
    }

    /**
     * Requests the authoritative start from any ts3j instance in the channel.
     * Unlike a client-targeted request, this works when a restricted identity
     * cannot discover the other client's id or metadata.
     */
    private void queueChannelSessionMarkerRequest(final LocalTeamspeakClientSocket expectedSocket,
                                                  final int channelId) {
        if (expectedSocket == null || channelId < 0) return;
        ioExecutor.submit(new Runnable() {
            @Override
            public void run() {
                sendChannelSessionMarkerRequest(expectedSocket, channelId);
            }
        });
    }

    /**
     * Retries a local rejoin handshake without blocking the protocol executor.
     * A marker can race the initial snapshot or be lost together with a UDP
     * notification; two short retries cover that window while stopping once a
     * known shared start has been adopted.
     */
    private void scheduleChannelSessionMarkerRetries(final LocalTeamspeakClientSocket expectedSocket,
                                                     final int channelId) {
        if (expectedSocket == null || channelId < 0 || closed) return;
        long[] delays = {400L, 1400L};
        for (long delay : delays) {
            try {
                sessionMarkerRetryExecutor.schedule(new Runnable() {
                    @Override
                    public void run() {
                        if (closed || !needsSessionMarkerRetry(channelId)) return;
                        ioExecutor.submit(() -> sendChannelSessionMarkerRequest(expectedSocket,
                                channelId));
                    }
                }, delay, TimeUnit.MILLISECONDS);
            } catch (RuntimeException ignored) {
                // Closing the gateway races only with optional retry tasks.
            }
        }
    }

    private boolean needsSessionMarkerRetry(int channelId) {
        VoiceRoomSession session = sessions.snapshot().get(
                new SessionKey(configuredServerId(), channelId));
        if (session == null || !session.isOccupied() || !session.isStartKnown()) return true;
        return permissionsLimited && session.getPresentUsers().size() <= 1;
    }

    private void sendChannelSessionMarkerRequest(LocalTeamspeakClientSocket expectedSocket,
                                                 int channelId) {
        try {
            if (socket != expectedSocket || closed || initialSync || !sessionStateReady) return;
            // This request is deliberately emitted for every join or rejoin
            // event. Suppressing the first request would lose the only
            // response when the peer leaves immediately afterward.
            expectedSocket.sendChannelMessage(channelId, sessionChannelMarkerRequest(channelId));
        } catch (Throwable ignored) {
            // The shared marker is best effort; normal chat remains unaffected.
        }
    }

    private void requestPeerSessionMarkers(LocalTeamspeakClientSocket expectedSocket,
                                           Map<Integer, ClientView> knownClients) {
        if (expectedSocket == null || knownClients == null) return;
        int localId = expectedSocket.getClientId();
        for (ClientView client : knownClients.values()) {
            if (client == null || client.getId() < 0 || client.getId() == localId
                    || client.getChannelId() < 0) continue;
            queuePeerSessionMarker(expectedSocket, client.getId(), client.getChannelId());
        }
    }

    private void queuePeerSessionMarker(final LocalTeamspeakClientSocket expectedSocket,
                                        final int peerId, final int channelId) {
        if (expectedSocket == null || peerId < 0 || channelId < 0) return;
        ioExecutor.submit(new Runnable() {
            @Override
            public void run() {
                try {
                    if (socket != expectedSocket) return;
                    if (initialSync || !sessionStateReady) return;
                    // Ask explicitly first. This works even when clientinfo
                    // or client metadata is hidden by the server's limited
                    // visibility permissions.
                    sendSessionMarkerRequest(expectedSocket, peerId, channelId);

                    String marker = sessionMarker(channelId);
                    if (marker == null) return;
                    // The marker has a private, namespaced payload and is
                    // ignored by other ts3j instances unless they recognize
                    // it. Do not require clientinfo/client_meta_data here:
                    // restricted identities can receive live events while
                    // being unable to inspect the peer that just joined.
                    if (!rememberSessionMarkerSend("marker:" + peerId + ":"
                            + channelId + ":" + marker)) return;
                    expectedSocket.sendPrivateMessage(peerId, marker);
                } catch (Throwable ignored) {
                    // The marker is an optional convergence aid.
                }
            }
        });
    }

    private boolean rememberSessionMarkerSend(String sendKey) {
        if (sendKey == null || sendKey.isEmpty()) return false;
        synchronized (this) {
            Instant previous = recentSessionMarkerSends.get(sendKey);
            Instant now = clock.instant();
            if (previous != null && !now.minusSeconds(10L).isAfter(previous)) return false;
            recentSessionMarkerSends.put(sendKey, now);
            if (recentSessionMarkerSends.size() > 512) recentSessionMarkerSends.clear();
            return true;
        }
    }

    private void rememberRecentSessionMarkerPeerRequest(String serverId, int channelId,
                                                        int peerId) {
        if (serverId == null || serverId.isEmpty() || channelId < 0 || peerId < 0) return;
        synchronized (this) {
            recentSessionMarkerPeerRequests.put(sessionMarkerPeerKey(serverId, channelId, peerId),
                    clock.instant());
            if (recentSessionMarkerPeerRequests.size() > 256) {
                recentSessionMarkerPeerRequests.clear();
            }
        }
    }

    private boolean hasRecentSessionMarkerPeerRequest(String serverId, int channelId,
                                                      int peerId) {
        String key = sessionMarkerPeerKey(serverId, channelId, peerId);
        synchronized (this) {
            Instant requestedAt = recentSessionMarkerPeerRequests.get(key);
            if (requestedAt == null) return false;
            if (clock.instant().minusSeconds(15L).isAfter(requestedAt)) {
                recentSessionMarkerPeerRequests.remove(key);
                return false;
            }
            return true;
        }
    }

    private void forgetRecentSessionMarkerPeerRequest(String serverId, int channelId,
                                                      int peerId) {
        synchronized (this) {
            recentSessionMarkerPeerRequests.remove(sessionMarkerPeerKey(serverId, channelId, peerId));
        }
    }

    private static String sessionMarkerPeerKey(String serverId, int channelId, int peerId) {
        return serverId + "\u0000" + channelId + "\u0000" + peerId;
    }

    private void clearSessionMarkerNegotiationAfterLeave(String serverId, int channelId,
                                                          int clientId) {
        if (serverId == null || serverId.isEmpty() || channelId < 0) return;
        SessionKey key = new SessionKey(serverId, channelId);
        synchronized (this) {
            if (clientId >= 0) {
                recentSessionMarkerPeerRequests.remove(
                        sessionMarkerPeerKey(serverId, channelId, clientId));
            }
            VoiceRoomSession session = sessions.snapshot().get(key);
            if (session != null && session.isOccupied()) return;
            pendingSessionMarkers.remove(key);
            pendingServerSessionMarkers.remove(key);
            latestServerSessionStarts.remove(key);
            pendingSessionMarkerRequests.remove(key);
            pendingSessionChannelRequests.remove(key);
            String prefix = serverId + "\u0000" + channelId + "\u0000";
            recentSessionMarkerPeerRequests.keySet().removeIf(value -> value.startsWith(prefix));
        }
    }

    private void discardPendingSessionMarkersForEmptyChannels(String serverId,
                                                               Map<Integer, ? extends java.util.Collection<Integer>> snapshot) {
        if (serverId == null || serverId.isEmpty()) return;
        synchronized (this) {
            Set<SessionKey> keys = new HashSet<>();
            for (SessionKey key : pendingSessionMarkers.keySet()) {
                if (key.getServerId().equals(serverId)) keys.add(key);
            }
            for (SessionKey key : keys) {
                java.util.Collection<Integer> users = snapshot == null ? null
                        : snapshot.get(key.getChannelId());
                if (users == null || users.isEmpty()) {
                    pendingSessionMarkers.remove(key);
                    pendingServerSessionMarkers.remove(key);
                    latestServerSessionStarts.remove(key);
                    pendingSessionMarkerRequests.remove(key);
                    pendingSessionChannelRequests.remove(key);
                    String prefix = serverId + "\u0000" + key.getChannelId() + "\u0000";
                    recentSessionMarkerPeerRequests.keySet()
                            .removeIf(value -> value.startsWith(prefix));
                }
            }
        }
    }

    private String sessionMarker(int channelId) {
        SessionKey key = new SessionKey(configuredServerId(), channelId);
        VoiceRoomSession session = sessions.snapshot().get(key);
        if (session == null || !session.isOccupied() || !session.isStartKnown()
                || session.getVoiceSessionStart() == null) return null;
        String encodedServer = Base64.getUrlEncoder().withoutPadding().encodeToString(
                key.getServerId().getBytes(java.nio.charset.StandardCharsets.UTF_8));
        return SESSION_MARKER_PREFIX + encodedServer + "|" + channelId + "|"
                + session.getVoiceSessionStart();
    }

    private String sessionMarkerRequest(int channelId) {
        String serverId = configuredServerId();
        String encodedServer = Base64.getUrlEncoder().withoutPadding().encodeToString(
                serverId.getBytes(java.nio.charset.StandardCharsets.UTF_8));
        return SESSION_MARKER_REQUEST_PREFIX + encodedServer + "|" + channelId;
    }

    private String sessionChannelMarkerRequest(int channelId) {
        String serverId = configuredServerId();
        String encodedServer = Base64.getUrlEncoder().withoutPadding().encodeToString(
                serverId.getBytes(java.nio.charset.StandardCharsets.UTF_8));
        return SESSION_CHANNEL_REQUEST_PREFIX + encodedServer + "|" + channelId;
    }

    /**
     * A full-client notifytextmessage has no target field for channel chat.
     * Resolve it from the sender's current channel first; the local channel is
     * the final fallback for servers that do not expose the sender in the
     * subscription snapshot.
     */
    private synchronized int resolveChannelFromTextEvent(TextMessageEvent event) {
        ClientView sender = clients.get(event.getInvokerId());
        if (sender != null && sender.getChannelId() >= 0) return sender.getChannelId();
        return currentChannelId;
    }

    private void appendChannelMessage(ChannelTextMessage message) {
        List<ChannelTextMessage> messages = channelMessages.get(message.getChannelId());
        if (messages == null) {
            messages = new ArrayList<>();
            channelMessages.put(message.getChannelId(), messages);
        }
        messages.add(message);
        while (messages.size() > MAX_CHAT_MESSAGES) {
            messages.remove(0);
            Integer boundary = channelHistoryBoundaries.get(message.getChannelId());
            if (boundary != null) {
                channelHistoryBoundaries.put(message.getChannelId(), Math.max(0, boundary - 1));
            }
        }
    }

    private boolean appendChannelMessageIfNew(ChannelTextMessage message) {
        if (hasRecentMessage(message.getChannelId(), message.getMessage())) return false;
        appendChannelMessage(message);
        return true;
    }

    private boolean hasRecentMessage(int channelId, String message) {
        List<ChannelTextMessage> messages = channelMessages.get(channelId);
        if (messages == null || messages.isEmpty()) return false;
        ChannelTextMessage last = messages.get(messages.size() - 1);
        if (!message.equals(last.getMessage())) return false;
        Instant now = clock.instant();
        Instant receivedAt = last.getReceivedAt();
        return !now.isBefore(receivedAt) && !now.minusSeconds(5).isAfter(receivedAt);
    }

    private void loadChatHistory(String serverId) {
        try {
            Map<Integer, List<ChannelTextMessage>> loaded = chatRepository.load(serverId);
            for (Map.Entry<Integer, List<ChannelTextMessage>> entry : loaded.entrySet()) {
                List<ChannelTextMessage> messages = entry.getValue() == null
                        ? new ArrayList<ChannelTextMessage>()
                        : new ArrayList<>(entry.getValue());
                while (messages.size() > MAX_CHAT_MESSAGES) messages.remove(0);
                if (!messages.isEmpty()) {
                    channelMessages.put(entry.getKey(), messages);
                    channelHistoryBoundaries.put(entry.getKey(), messages.size());
                }
            }
        } catch (IOException error) {
            chatHistoryWarning = "No se pudo cargar el historial local del chat.";
        }
    }

    private void persistChannelMessage(String serverId, ChannelTextMessage message) {
        if (serverId == null || serverId.isEmpty() || message == null) return;
        try {
            chatRepository.append(serverId, message);
        } catch (IOException error) {
            synchronized (this) {
                chatHistoryWarning = "No se pudo guardar el historial local del chat.";
            }
        }
    }

    private synchronized String configuredServerId() {
        return config == null ? "" : config.serverId();
    }

    private void refreshFromServer(LocalTeamspeakClientSocket current) throws Exception {
        Map<Integer, ChannelView> loadedChannels = new HashMap<>();
        boolean channelListLoaded = false;
        boolean limited = permissionsLimited;
        try {
            for (Channel channel : current.listChannels()) {
                Channel detailed = loadChannelDetails(current, channel);
                loadedChannels.put(channel.getId(), toChannelView(detailed, null));
            }
            channelListLoaded = true;
        } catch (Throwable error) {
            if (!isInsufficientClientPermissions(error)) throw error;
            limited = true;
        }
        Map<Integer, ClientView> loadedClients = new HashMap<>();
        boolean clientListLoaded = false;
        try {
            for (Client client : current.listClients()) {
                ClientView view = toClient(client);
                // ServerQuery connections are protocol helpers, not people in
                // the voice room. Excluding them here keeps the occupancy
                // snapshot and the rendered roster in agreement.
                if (!isRealClient(view)) {
                    nonUserClientIds.add(view.getId());
                    continue;
                }
                loadedClients.put(view.getId(), view);
            }
            clientListLoaded = true;
        } catch (Throwable error) {
            if (!isInsufficientClientPermissions(error)) throw error;
            limited = true;
        }

        // A guest identity may be allowed to connect and receive events while
        // channellist/clientlist are denied. Ask only for our own record and
        // the channel we are actually in, which is permitted on TeamSpeak 3
        // servers with that common permission layout.
        Client localFallback = null;
        ChannelView currentChannelFallback = null;
        if (limited) {
            try {
                localFallback = current.getClientInfo(current.getClientId());
            } catch (Throwable ignored) {
                // The event snapshot remains the best available source.
            }
            if (localFallback != null && localFallback.getChannelId() >= 0) {
                try {
                    Channel detailed = current.getChannelInfo(localFallback.getChannelId());
                    if (detailed != null) {
                        Map<String, String> properties = new HashMap<>(detailed.getMap());
                        properties.put("cid", Integer.toString(localFallback.getChannelId()));
                        currentChannelFallback = toChannelView(new Channel(properties), null);
                    }
                } catch (Throwable ignored) {
                    // Keep any channel-list event already received.
                }
            }
        }

        Map<Integer, ClientView> effectiveClients;
        synchronized (this) {
            if (channelListLoaded) {
                channels.clear();
                channels.putAll(loadedChannels);
            } else if (currentChannelFallback != null) {
                channels.put(currentChannelFallback.getId(), currentChannelFallback);
            }
            if (clientListLoaded) {
                clients.clear();
                clients.putAll(loadedClients);
            } else if (localFallback != null) {
                clients.put(localFallback.getId(), toClient(localFallback));
            }
            effectiveClients = new HashMap<>(clients);
            currentChannelId = findLocalChannel(current.getClientId());
            status = currentChannelId >= 0
                    ? ConnectionStatus.CONNECTED_IN_CHANNEL : ConnectionStatus.CONNECTED_NO_CHANNEL;
            permissionsLimited = limited;
        }
        if (audioBridge != null) {
            ClientView localView = effectiveClients.get(current.getClientId());
            audioBridge.setMuted(localView != null && localView.isInputMuted());
            audioBridge.setOutputMuted(localView != null && localView.isOutputMuted());
        }
        Map<Integer, List<Integer>> usersByChannel = new TreeMap<>();
        for (ClientView view : effectiveClients.values()) {
            if (view.getChannelId() >= 0) {
                List<Integer> users = usersByChannel.get(view.getChannelId());
                if (users == null) {
                    users = new ArrayList<>();
                    usersByChannel.put(view.getChannelId(), users);
                }
                users.add(view.getId());
            }
        }
        Map<Integer, java.util.Collection<Integer>> snapshot = new LinkedHashMap<>();
        snapshot.putAll(usersByChannel);
        sessions.reconcile(config.serverId(), snapshot, clock.instant(),
                gatewayEventId("snapshot", Collections.<String, String>emptyMap()), 0L,
                current.getClientId());
        discardPendingSessionMarkersForEmptyChannels(config.serverId(), snapshot);
        // A marker may have arrived while the snapshot was being assembled.
        // Apply once before and once after publishing readiness so a marker
        // queued during the transition cannot be stranded.
        applyPendingSessionMarkers();
        applyPendingServerSessionMarkers();
        initialSync = false;
        sessionStateReady = true;
        applyPendingSessionMarkers();
        applyPendingServerSessionMarkers();
        respondToPendingSessionMarkerRequests();
        requestPeerSessionMarkers(current, effectiveClients);
        if (currentChannelId >= 0) {
            queueChannelSessionMarkerRequest(current, currentChannelId);
            scheduleChannelSessionMarkerRetries(current, currentChannelId);
            respondToChannelSessionMarkerRequest(currentChannelId);
        }
        publish();
    }

    @Override
    public void onChannelList(ChannelListEvent event) {
        Channel channel = new Channel(event.getMap());
        synchronized (this) {
            channels.put(channel.getId(), toChannelView(channel, channels.get(channel.getId())));
        }
        // Channel list notifications are intentionally small on some TeamSpeak
        // servers and omit channel_codec. Ask for the authoritative channelinfo
        // record without blocking the socket event thread.
        if (channel.getCodec() == Codec.UNKNOWN) {
            LocalTeamspeakClientSocket current = socket;
            if (current != null) {
                ioExecutor.submit(() -> enrichChannel(current, channel.getId()));
            }
        }
        publish();
    }

    private void enrichChannel(LocalTeamspeakClientSocket expectedSocket, int channelId) {
        try {
            Channel listed = new Channel(Collections.singletonMap("cid", Integer.toString(channelId)));
            Channel detailed = loadChannelDetails(expectedSocket, listed);
            if (detailed == listed) return;
            synchronized (this) {
                if (socket != expectedSocket) return;
                ChannelView previous = channels.get(channelId);
                channels.put(channelId, toChannelView(detailed, previous));
            }
            publish();
        } catch (Throwable ignored) {
            // A partial event is still useful; the next authoritative refresh
            // will retry the channelinfo lookup.
        }
    }

    private Channel loadChannelDetails(LocalTeamspeakClientSocket current, Channel listed) {
        if (listed.getCodec() != Codec.UNKNOWN) return listed;
        try {
            Channel detailed = current.getChannelInfo(listed.getId());
            if (detailed == null) return listed;
            Map<String, String> properties = new HashMap<>(detailed.getMap());
            // ts3j's getChannelInfo response carries the channel properties but
            // not cid. Keep the id from channellist so Channel#getId remains valid.
            properties.put("cid", Integer.toString(listed.getId()));
            return new Channel(properties);
        } catch (Throwable ignored) {
            return listed;
        }
    }

    @Override
    public void onChannelCreate(ChannelCreateEvent event) {
        onChannelList(new ChannelListEvent(event.getMap()));
    }

    @Override
    public void onChannelEdit(ChannelEditedEvent event) {
        onChannelList(new ChannelListEvent(event.getMap()));
    }

    @Override
    public void onChannelDeleted(ChannelDeletedEvent event) {
        synchronized (this) {
            channels.remove(event.getChannelId());
        }
        publish();
    }

    @Override
    public void onClientJoin(ClientJoinEvent event) {
        if (isDuplicate("join", event.getMap())) return;
        Client client = new Client(event.getMap());
        if (client.getType() != 0) {
            nonUserClientIds.add(client.getId());
            return;
        }
        int channelId = event.getClientTargetId() >= 0
                ? event.getClientTargetId() : client.getChannelId();
        ClientView view = toClient(client, channelId);
        boolean sync = initialSync;
        int previousCurrentChannel;
        boolean localClient;
        synchronized (this) {
            ClientView previous = clients.get(view.getId());
            // A move is represented by notifyclientmoved in ts3j. If a late
            // join notification arrives for a client already tracked in a
            // different channel, keep the newer local route until the next
            // authoritative listClients() reconciliation.
            if (previous != null && previous.getChannelId() != channelId) return;
            previousCurrentChannel = currentChannelId;
            localClient = view.getId() == localClientId();
            clients.put(view.getId(), view);
            if (localClient) currentChannelId = channelId;
        }
        if (channelId >= 0 && config != null) {
            sessions.join(config.serverId(), channelId, view.getId(), clock.instant(),
                    sync, gatewayEventId("join", event.getMap()), 0L);
        }
        if (!localClient && channelId >= 0 && !sync) {
            queuePeerSessionMarker(socket, view.getId(), channelId);
        }
        applyPendingSessionMarkers();
        applyPendingServerSessionMarkers();
        respondToPendingSessionMarkerRequests();
        if (!sync && channelId >= 0) {
            queueChannelSessionMarkerRequest(socket, channelId);
            if (localClient) scheduleChannelSessionMarkerRetries(socket, channelId);
            // If this instance already knows the session start, answer the
            // fresh join immediately as well as requesting it. This removes a
            // race where the rejoining client leaves before the request's
            // response is delivered.
            respondToChannelSessionMarkerRequest(channelId);
        }
        if (!sync && previousCurrentChannel >= 0 && !localClient
                && channelId == previousCurrentChannel) {
            emitActivity(new TeamSpeakActivity(TeamSpeakActivity.Type.CLIENT_JOINED_CURRENT_CHANNEL,
                    view.getNickname(), "", channelName(channelId), serverName()));
        }
        refreshStatus();
    }

    @Override
    public void onClientMoved(ClientMovedEvent event) {
        if (isDuplicate("move", event.getMap())) return;
        int clientId = event.getClientId();
        int target = event.getTargetChannelId();
        int from = mapInt(event.getMap(), "cfid", -1);
        boolean sync = initialSync;
        int previousCurrentChannel;
        boolean localClient;
        String nickname;
        synchronized (this) {
            ClientView previous = clients.get(clientId);
            if (nonUserClientIds.contains(clientId)
                    || (previous != null && !isRealClient(previous))
                    || mapInt(event.getMap(), "client_type", 0) != 0) {
                if (mapInt(event.getMap(), "client_type", 0) != 0) {
                    nonUserClientIds.add(clientId);
                }
                clients.remove(clientId);
                publish();
                return;
            }
            if (from < 0 && previous != null) from = previous.getChannelId();
            ClientView old = previous == null ? null : previous;
            previousCurrentChannel = currentChannelId;
            localClient = clientId == localClientId();
            nickname = old == null ? "Usuario " + clientId : old.getNickname();
            clients.put(clientId, new ClientView(clientId, target,
                    nickname,
                    old == null ? "" : old.getUniqueIdentifier(),
                    old == null ? 0 : old.getType(),
                    old != null && old.isInputMuted(), old != null && old.isOutputMuted(),
                    old != null && old.isAway()));
            if (localClient) currentChannelId = target;
        }
        if (config != null && target >= 0) {
            sessions.move(config.serverId(), from, target, clientId, clock.instant(),
                    sync, gatewayEventId("move", event.getMap()), 0L);
        }
        if (!localClient && target >= 0 && !sync) {
            queuePeerSessionMarker(socket, clientId, target);
        }
        applyPendingSessionMarkers();
        applyPendingServerSessionMarkers();
        respondToPendingSessionMarkerRequests();
        if (!sync && target >= 0) {
            queueChannelSessionMarkerRequest(socket, target);
            if (localClient) scheduleChannelSessionMarkerRetries(socket, target);
            respondToChannelSessionMarkerRequest(target);
        }
        if (!sync && !localClient && previousCurrentChannel >= 0) {
            if (target == previousCurrentChannel && from != previousCurrentChannel) {
                emitActivity(new TeamSpeakActivity(TeamSpeakActivity.Type.CLIENT_SWITCHED_TO_CURRENT_CHANNEL,
                        nickname, channelName(from), channelName(target), serverName()));
            } else if (from == previousCurrentChannel && target != previousCurrentChannel) {
                emitActivity(new TeamSpeakActivity(TeamSpeakActivity.Type.CLIENT_SWITCHED_FROM_CURRENT_CHANNEL,
                        nickname, channelName(from), channelName(target), serverName()));
            }
        } else if (!sync && localClient && target >= 0 && target != from) {
            emitActivity(new TeamSpeakActivity(TeamSpeakActivity.Type.YOU_SWITCHED_CHANNEL,
                    "", channelName(from), channelName(target), serverName()));
        }
        refreshStatus();
    }

    @Override
    public void onClientLeave(ClientLeaveEvent event) {
        if (isDuplicate("leave", event.getMap())) return;
        int clientId = event.getClientId();
        int from = event.getClientFromId();
        boolean sync = initialSync;
        int previousCurrentChannel;
        boolean localClient;
        String nickname;
        synchronized (this) {
            ClientView previous = clients.get(clientId);
            if (nonUserClientIds.remove(clientId)
                    || (previous != null && !isRealClient(previous))
                    || mapInt(event.getMap(), "client_type", 0) != 0) {
                clients.remove(clientId);
                publish();
                return;
            }
            clients.remove(clientId);
            if (from < 0 && previous != null) from = previous.getChannelId();
            previousCurrentChannel = currentChannelId;
            localClient = clientId == localClientId();
            nickname = previous == null ? "Usuario " + clientId : previous.getNickname();
            if (localClient) currentChannelId = -1;
        }
        if (config != null) {
            sessions.leave(config.serverId(), from, clientId, clock.instant(),
                    gatewayEventId("leave", event.getMap()), 0L);
            clearSessionMarkerNegotiationAfterLeave(config.serverId(), from, clientId);
        }
        if (!sync && !localClient && from >= 0 && from == previousCurrentChannel) {
            emitActivity(new TeamSpeakActivity(TeamSpeakActivity.Type.CLIENT_LEFT_CURRENT_CHANNEL,
                    nickname, channelName(from), "", serverName()));
        }
        if (!sync && from >= 0) {
            queueChannelSessionMarkerRequest(socket, from);
        }
        refreshStatus();
    }

    @Override
    public void onClientChanged(ClientUpdatedEvent event) {
        int clientId = event.getClientId();
        TeamSpeakActivity inputActivity = null;
        TeamSpeakActivity outputActivity = null;
        TeamSpeakActivity awayActivity = null;
        synchronized (this) {
            if (nonUserClientIds.contains(clientId)) return;
            ClientView previous = clients.get(clientId);
            if (previous != null && isRealClient(previous)) {
                Client raw = new Client(event.getMap());
                boolean inputMuted = hasClientFlag(event.getMap(), "client_input_muted", previous.isInputMuted());
                boolean outputMuted = hasClientFlag(event.getMap(), "client_output_muted", previous.isOutputMuted());
                boolean away = hasClientFlag(event.getMap(), "client_away", previous.isAway());
                boolean localClient = clientId == localClientId();
                clients.put(clientId, new ClientView(clientId, previous.getChannelId(),
                        raw.getNickname().isEmpty() ? previous.getNickname() : raw.getNickname(),
                        previous.getUniqueIdentifier(),
                        previous.getType(), inputMuted, outputMuted, away));
                if (!initialSync && localClient) {
                    if (previous.isInputMuted() != inputMuted
                            && event.getMap().containsKey("client_input_muted")) {
                        inputActivity = activityForClientFlag("client_input_muted", inputMuted);
                    }
                    if (previous.isOutputMuted() != outputMuted
                            && event.getMap().containsKey("client_output_muted")) {
                        outputActivity = activityForClientFlag("client_output_muted", outputMuted);
                    }
                    if (previous.isAway() != away && event.getMap().containsKey("client_away")) {
                        awayActivity = activityForClientFlag("client_away", away);
                    }
                }
            }
        }
        emitActivity(inputActivity);
        emitActivity(outputActivity);
        emitActivity(awayActivity);
        publish();
    }

    @Override
    public void onClientPoke(ClientPokeEvent event) {
        String nickname = event.getInvokerName();
        if (nickname == null || nickname.trim().isEmpty()) nickname = "Usuario";
        emitActivity(new TeamSpeakActivity(TeamSpeakActivity.Type.POKE,
                nickname, "", "", serverName()));
    }

    @Override
    public void onDisconnected(DisconnectedEvent event) {
        int localId = localClientId();
        int channelId;
        String server = serverName();
        synchronized (this) {
            channelId = currentChannelId;
        }
        if (config != null && localId >= 0 && channelId >= 0) {
            sessions.leave(config.serverId(), channelId, localId, clock.instant(),
                    gatewayEventId("disconnect", Collections.<String, String>emptyMap()), 0L);
            clearSessionMarkerNegotiationAfterLeave(config.serverId(), channelId, localId);
        }
        synchronized (this) {
            status = ConnectionStatus.DISCONNECTED;
            currentChannelId = -1;
            clients.clear();
            nonUserClientIds.clear();
            channels.clear();
            channelMessages.clear();
            channelHistoryBoundaries.clear();
            chatHistoryWarning = "";
            permissionsLimited = false;
            pendingSessionMarkers.clear();
            pendingServerSessionMarkers.clear();
            latestServerSessionStarts.clear();
            pendingSessionMarkerRequests.clear();
            recentSessionMarkerSends.clear();
            recentSessionMarkerPeerRequests.clear();
            if (audioBridge != null) audioBridge.close();
            audioBridge = null;
            initialSync = false;
            sessionStateReady = true;
        }
        emitActivity(new TeamSpeakActivity(TeamSpeakActivity.Type.DISCONNECTED,
                "", "", "", server));
        publish();
    }

    private void refreshStatus() {
        synchronized (this) {
            if (status == ConnectionStatus.ERROR || status == ConnectionStatus.DISCONNECTED) {
                publish();
                return;
            }
            status = currentChannelId >= 0
                    ? ConnectionStatus.CONNECTED_IN_CHANNEL : ConnectionStatus.CONNECTED_NO_CHANNEL;
        }
        publish();
    }

    private int localClientId() {
        LocalTeamspeakClientSocket current = socket;
        return current == null ? -1 : current.getClientId();
    }

    private TeamSpeakActivity activity(TeamSpeakActivity.Type type, String client,
                                       String fromChannel, String channel) {
        return new TeamSpeakActivity(type, client, fromChannel, channel, serverName());
    }

    private synchronized String channelName(int channelId) {
        ChannelView channel = channels.get(channelId);
        return channel == null ? "Canal " + channelId : channel.getName();
    }

    private synchronized String serverName() {
        return config == null ? "" : config.getHost();
    }

    private synchronized CodecType currentVoiceCodec() {
        ChannelView channel = channels.get(currentChannelId);
        if (channel == null || channel.getCodec() == null || channel.getCodec().trim().isEmpty()) {
            return CodecType.OPUS_VOICE;
        }
        try {
            return CodecType.valueOf(channel.getCodec().trim().toUpperCase(Locale.ROOT));
        } catch (IllegalArgumentException ignored) {
            return CodecType.OPUS_VOICE;
        }
    }

    private synchronized double currentVoiceVolumeDb(int clientId) {
        if (clientVolumeStore == null || config == null) return 0.0D;
        return clientVolumeStore.get(config.serverId(), clients.get(clientId));
    }

    private void emitActivity(TeamSpeakActivity activity) {
        if (activity == null || activityListeners.isEmpty()) return;
        Instant now = clock.instant();
        synchronized (this) {
            // Each local send is a distinct user action even when several
            // messages share the same sender/channel signature. Other
            // protocol activities remain protected by the short duplicate
            // suppression window.
            if (activity.getType() != TeamSpeakActivity.Type.CHAT_SENT) {
                String signature = activity.signature();
                Instant previous = recentActivitySignatures.get(signature);
                recentActivitySignatures.put(signature, now);
                if (previous != null && !now.isBefore(previous)
                        && now.minusSeconds(2L).isBefore(previous)) return;
            }
            if (recentActivitySignatures.size() > 512) recentActivitySignatures.clear();
        }
        for (Consumer<TeamSpeakActivity> listener : activityListeners) {
            try {
                listener.accept(activity);
            } catch (RuntimeException ignored) {
                // A notification adapter must never break protocol processing.
            }
        }
    }

    private int findLocalChannel(int localId) {
        ClientView local = clients.get(localId);
        return local == null ? -1 : local.getChannelId();
    }

    private long nextSequence() {
        return ++eventSequence;
    }

    private String gatewayEventId(String type, Map<String, String> map) {
        return eventSource + ":" + nextSequence() + ":" + eventSignature(type, map);
    }

    private boolean isDuplicate(String type, Map<String, String> map) {
        String signature = eventSignature(type, map);
        Instant now = clock.instant();
        synchronized (this) {
            Instant previous = recentEventSignatures.get(signature);
            recentEventSignatures.put(signature, now);
            if (previous != null && !now.isBefore(previous)
                    && now.minusSeconds(2).isBefore(previous)) return true;
            if (recentEventSignatures.size() > 512) recentEventSignatures.clear();
        }
        return false;
    }

    private static String eventSignature(String type, Map<String, String> map) {
        List<String> entries = new ArrayList<>();
        for (Map.Entry<String, String> entry : map.entrySet()) {
            entries.add(entry.getKey() + "=" + entry.getValue());
        }
        Collections.sort(entries);
        return type + "|" + entries;
    }

    private static int mapInt(Map<String, String> map, String key, int fallback) {
        try {
            String value = map.get(key);
            return value == null || value.isEmpty() ? fallback : Integer.parseInt(value);
        } catch (NumberFormatException ignored) {
            return fallback;
        }
    }

    static ChannelView toChannelView(Channel channel, ChannelView previous) {
        Codec codec = channel.getCodec();
        boolean voice = codec != Codec.UNKNOWN
                || (previous != null && previous.isVoiceCapable());
        String codecName = codec == Codec.UNKNOWN && previous != null
                ? previous.getCodec() : codec.name();
        return new ChannelView(channel.getId(), channel.getParentChannelId(), channel.getOrder(),
                channel.getName(), voice, codecName);
    }

    private ClientView toClient(Client client) {
        return toClient(client, client.getChannelId());
    }

    private ClientView toClient(Client client, int channelId) {
        return new ClientView(client.getId(), channelId, client.getNickname(), client.getUniqueIdentifier(), client.getType(),
                client.isInputMuted(), client.isOutputMuted(), client.isAway());
    }

    private static boolean hasClientFlag(Map<String, String> map, String key, boolean fallback) {
        if (map == null || !map.containsKey(key)) return fallback;
        String value = map.get(key);
        return "1".equals(value) || "true".equalsIgnoreCase(value);
    }

    private synchronized GatewaySnapshot createSnapshot() {
        Map<Integer, ChannelView> sortedChannels = new TreeMap<>(channels);
        Map<Integer, ClientView> sortedClients = new TreeMap<>(clients);
        String visibleError = errorMessage.isEmpty() ? chatHistoryWarning : errorMessage;
        return new GatewaySnapshot(status, config == null ? "" : config.serverId(), visibleError,
                localClientId(), currentChannelId, sortedChannels, sortedClients,
                sessions.snapshot(), channelMessages, channelHistoryBoundaries,
                sessionStateReady, permissionsLimited);
    }

    private void publish() {
        GatewaySnapshot current = snapshot();
        for (Consumer<GatewaySnapshot> listener : listeners) listener.accept(current);
    }

    private LocalIdentity loadIdentity() throws IOException, GeneralSecurityException {
        Optional<LocalIdentity> officialIdentity = OfficialIdentityImporter.tryLoadDefault();
        if (officialIdentity.isPresent()) return officialIdentity.get();

        Path identityPath = Paths.get(System.getProperty("user.home"), ".ts3j-client", "identity.ini");
        return loadOrCreateIdentity(identityPath);
    }

    private static Path defaultChatHistoryDirectory() {
        return Paths.get(System.getProperty("user.home"), ".ts3j-client", "chat-history");
    }

    static LocalIdentity loadOrCreateIdentity(Path identityPath)
            throws IOException, GeneralSecurityException {
        if (identityPath == null) throw new IllegalArgumentException("identityPath");
        Files.createDirectories(identityPath.getParent());
        boolean created = !Files.exists(identityPath);
        LocalIdentity identity = created
                ? LocalIdentity.generateNew(MINIMUM_IDENTITY_SECURITY)
                : LocalIdentity.read(identityPath.toFile());
        if (created || identity.getSecurityLevel() < MINIMUM_IDENTITY_SECURITY) {
            identity.improveSecurity(MINIMUM_IDENTITY_SECURITY);
            identity.save(identityPath.toFile());
        }
        return identity;
    }

    private static String friendlyMessage(Throwable error) {
        Throwable cause = error;
        while (cause.getCause() != null && (cause.getMessage() == null || cause.getMessage().isEmpty())) {
            cause = cause.getCause();
        }
        String message = cause.getMessage();
        if (message != null) {
            String normalized = message.toLowerCase(Locale.ROOT);
            if (normalized.contains("insufficient client permissions")) {
                return "El servidor aceptó la conexión, pero esta identidad no tiene permisos "
                        + "para consultar todos los canales. Usa la identidad oficial de TeamSpeak 3.";
            }
            if (normalized.contains("could not validate client identity")) {
                return "El servidor no pudo validar la identidad de TeamSpeak. "
                        + "Revisa la identidad oficial y vuelve a conectar.";
            }
            if (normalized.contains("timeout waiting for connected state")) {
                return "No hubo respuesta del servidor por UDP en el puerto 9987. "
                        + "El ping puede funcionar aunque UDP esté bloqueado: comprueba ZeroTier/VPN, "
                        + "el firewall y que TeamSpeak Server escuche en 9987/UDP. No requiere un certificado.";
            }
        }
        return message == null || message.isEmpty() ? cause.getClass().getSimpleName() : message;
    }

    private static boolean isInsufficientClientPermissions(Throwable error) {
        Throwable current = error;
        while (current != null) {
            String message = current.getMessage();
            if (message != null && message.toLowerCase(Locale.ROOT)
                    .contains("insufficient client permissions")) return true;
            current = current.getCause();
        }
        return false;
    }

    private static final class SessionMarker {
        private final String serverId;
        private final int channelId;
        private final Instant start;

        private SessionMarker(String serverId, int channelId, Instant start) {
            this.serverId = serverId;
            this.channelId = channelId;
            this.start = start;
        }
    }

    private static final class SessionMarkerRequest {
        private final String serverId;
        private final int channelId;

        private SessionMarkerRequest(String serverId, int channelId) {
            this.serverId = serverId;
            this.channelId = channelId;
        }
    }

    private static boolean isRealClient(ClientView view) {
        return view != null && view.getType() == 0;
    }

    private static final class ServerSessionMarker {
        private final String serverId;
        private final int channelId;
        private final String sessionId;
        private final Instant start;
        private final Instant serverNow;

        private ServerSessionMarker(String serverId, int channelId, String sessionId,
                                    Instant start, Instant serverNow) {
            this.serverId = serverId;
            this.channelId = channelId;
            this.sessionId = sessionId;
            this.start = start;
            this.serverNow = serverNow;
        }
    }

    private static final class SessionChannelRequest {
        private final String serverId;
        private final int channelId;

        private SessionChannelRequest(String serverId, int channelId) {
            this.serverId = serverId;
            this.channelId = channelId;
        }
    }

    private static final class PendingSessionMarker {
        private final Instant start;
        private final Instant receivedAt;
        private final int peerId;

        private PendingSessionMarker(Instant start, Instant receivedAt, int peerId) {
            this.start = start;
            this.receivedAt = receivedAt;
            this.peerId = peerId;
        }
    }

    private static final class PendingServerSessionMarker {
        private final Instant start;
        private final Instant receivedAt;
        private final String eventId;

        private PendingServerSessionMarker(Instant start, Instant receivedAt, String eventId) {
            this.start = start;
            this.receivedAt = receivedAt;
            this.eventId = eventId;
        }
    }

    private static void closeSocket(LocalTeamspeakClientSocket current) {
        try {
            current.close();
        } catch (IOException ignored) { }
    }

    @Override
    public void close() {
        closed = true;
        disconnect();
        sessionMarkerRetryExecutor.shutdownNow();
        ioExecutor.shutdownNow();
        try {
            ioExecutor.awaitTermination(2, TimeUnit.SECONDS);
        } catch (InterruptedException interrupted) {
            Thread.currentThread().interrupt();
        }
    }
}
